export type FreeConnector = {
  id: string;
  name: string;
  category: string;
  detail: string;
  endpoint: string;
  keyRequired: false;
};

const rows: Array<[string, string, string, string, string]> = [
  ["open-meteo", "Open-Meteo", "آب‌وهوا", "پیش‌بینی آب‌وهوا و داده‌های اقلیمی", "https://api.open-meteo.com/v1/forecast"],
  ["world-time", "World Time API", "آب‌وهوا و مکان", "زمان محلی مناطق مختلف", "https://worldtimeapi.org/api/timezone"],
  ["sunrise-sunset", "Sunrise-Sunset API", "آب‌وهوا و مکان", "طلوع و غروب خورشید", "https://api.sunrise-sunset.org/json"],
  ["nominatim", "Nominatim", "نقشه و مکان", "جست‌وجوی آدرس و مختصات", "https://nominatim.openstreetmap.org/search"],
  ["openstreetmap", "OpenStreetMap API", "نقشه و مکان", "داده‌های آزاد نقشه", "https://api.openstreetmap.org/api/0.6"],
  ["overpass", "Overpass API", "نقشه و مکان", "جست‌وجو در داده‌های OpenStreetMap", "https://overpass-api.de/api/interpreter"],
  ["ipify", "IPify", "آب‌وهوا و مکان", "دریافت IP عمومی", "https://api.ipify.org?format=json"],
  ["ip-api", "ip-api", "آب‌وهوا و مکان", "مکان تقریبی بر اساس IP", "http://ip-api.com/json"],
  ["openaq", "OpenAQ", "آب‌وهوا و مکان", "کیفیت هوای شهرها", "https://api.openaq.org/v3/locations"],
  ["usgs-earthquake", "USGS Earthquake API", "آب‌وهوا و مکان", "داده‌های زلزله‌ها", "https://earthquake.usgs.gov/fdsnws/event/1/query"],
  ["noaa-weather", "NOAA Weather API", "آب‌وهوا و مکان", "آب‌وهوا و اقلیم", "https://api.weather.gov"],
  ["solar-system", "Solar System OpenData", "آب‌وهوا و مکان", "دادهٔ اجرام منظومهٔ شمسی", "https://api.le-systeme-solaire.net/rest/bodies"],
  ["rest-countries", "REST Countries", "کشورها و ارز", "کشورها، پرچم، زبان و ارز", "https://restcountries.com/v3.1/all"],
  ["frankfurter", "Frankfurter", "کشورها و ارز", "نرخ تبدیل ارز", "https://api.frankfurter.app/latest"],
  ["nager-date", "Nager.Date", "کشورها و ارز", "تعطیلات رسمی کشورها", "https://date.nager.at/api/v3/PublicHolidays"],
  ["exchangerate-host", "ExchangeRate.host", "کشورها و ارز", "نرخ ارز و رمزارز", "https://api.frankfurter.app/latest"],
  ["currency-api", "Currency API", "کشورها و ارز", "نرخ‌های تبدیل ارز", "https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies"],
  ["universities", "Universities List", "کشورها و ارز", "فهرست دانشگاه‌ها", "http://universities.hipolabs.com/search"],
  ["agify", "Agify", "کشورها و ارز", "تخمین سن از روی نام", "https://api.agify.io"],
  ["genderize", "Genderize", "کشورها و ارز", "تخمین جنسیت از روی نام", "https://api.genderize.io"],
  ["nationalize", "Nationalize", "کشورها و ارز", "تخمین ملیت از روی نام", "https://api.nationalize.io"],
  ["open-library", "Open Library", "کتاب و پژوهش", "جست‌وجوی کتاب‌ها", "https://openlibrary.org/search.json"],
  ["open-library-covers", "Open Library Covers", "کتاب و پژوهش", "جلد کتاب‌ها", "https://covers.openlibrary.org"],
  ["gutendex", "Gutendex", "کتاب و پژوهش", "کتاب‌های Project Gutenberg", "https://gutendex.com/books"],
  ["wikimedia", "Wikimedia API", "کتاب و پژوهش", "داده‌های ویکیمدیا", "https://commons.wikimedia.org/w/api.php"],
  ["wikipedia", "Wikipedia REST API", "کتاب و پژوهش", "خلاصهٔ مقالات ویکی‌پدیا", "https://en.wikipedia.org/api/rest_v1/page/summary"],
  ["wikidata", "Wikidata", "کتاب و پژوهش", "داده‌های ساختاریافته", "https://www.wikidata.org/w/api.php"],
  ["dbpedia", "DBpedia", "کتاب و پژوهش", "داده‌های دانشنامه‌ای", "https://dbpedia.org/sparql"],
  ["internet-archive", "Internet Archive API", "کتاب و پژوهش", "جست‌وجو در آرشیو اینترنت", "https://archive.org/advancedsearch.php"],
  ["crossref", "Crossref API", "کتاب و پژوهش", "اطلاعات مقالات و DOI", "https://api.crossref.org/works"],
  ["openalex", "OpenAlex", "کتاب و پژوهش", "مقالات و پژوهش‌ها", "https://api.openalex.org/works"],
  ["europe-pmc", "Europe PMC", "کتاب و پژوهش", "منابع پزشکی و زیست‌پزشکی", "https://www.ebi.ac.uk/europepmc/webservices/rest/search"],
  ["pubmed", "PubMed API", "کتاب و پژوهش", "منابع پزشکی", "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"],
  ["gbif", "GBIF", "کتاب و پژوهش", "داده‌های تنوع زیستی", "https://api.gbif.org/v1/species"],
  ["jsonplaceholder", "JSONPlaceholder", "تست و توسعه", "دادهٔ آزمایشی REST", "https://jsonplaceholder.typicode.com/posts"],
  ["httpbin", "httpbin", "تست و توسعه", "آزمایش درخواست‌های HTTP", "https://httpbin.org/get"],
  ["kroki", "Kroki", "تست و توسعه", "تولید دیاگرام و نمودار", "https://kroki.io"],
  ["iconify", "Iconify", "تست و توسعه", "آیکون‌های SVG", "https://api.iconify.design"],
  ["npm", "NPM Registry API", "تست و توسعه", "پکیج‌های JavaScript", "https://registry.npmjs.org"],
  ["pypi", "PyPI JSON API", "تست و توسعه", "پکیج‌های Python", "https://pypi.org/pypi"],
  ["packagist", "Packagist API", "تست و توسعه", "پکیج‌های PHP", "https://repo.packagist.org"],
  ["jikan", "Jikan", "سرگرمی", "انیمه و مانگا", "https://api.jikan.moe/v4"],
  ["tvmaze", "TVMaze", "سرگرمی", "سریال‌ها و برنامه‌های تلویزیونی", "https://api.tvmaze.com"],
  ["rick-morty", "The Rick and Morty API", "سرگرمی", "شخصیت‌ها و قسمت‌ها", "https://rickandmortyapi.com/api"],
  ["swapi", "SWAPI", "سرگرمی", "اطلاعات Star Wars", "https://swapi.dev/api"],
  ["ghibli", "Studio Ghibli API", "سرگرمی", "فیلم‌های استودیو جیبلی", "https://ghibliapi.vercel.app"],
  ["pokeapi", "PokeAPI", "سرگرمی", "اطلاعات Pokémon", "https://pokeapi.co/api/v2"],
  ["anilist", "AniList API", "سرگرمی", "انیمه و مانگا", "https://graphql.anilist.co"],
  ["kitsu", "Kitsu API", "سرگرمی", "انیمه و مانگا", "https://kitsu.io/api/edge"],
  ["mangadex", "MangaDex API", "سرگرمی", "مانگا", "https://api.mangadex.org"],
  ["cheapshark", "CheapShark API", "سرگرمی", "قیمت بازی‌ها", "https://www.cheapshark.com/api/1.0"],
  ["free-to-game", "FreeToGame API", "سرگرمی", "بازی‌های رایگان", "https://www.freetogame.com/api"],
  ["scryfall", "Scryfall API", "سرگرمی", "کارت‌های Magic", "https://api.scryfall.com"],
  ["dog-ceo", "Dog CEO", "سرگرمی", "تصاویر سگ", "https://dog.ceo/api"],
  ["the-cat-api", "The Cat API", "سرگرمی", "تصاویر گربه", "https://api.thecatapi.com/v1"],
  ["cat-facts", "Cat Facts", "سرگرمی", "اطلاعات تصادفی دربارهٔ گربه", "https://catfact.ninja/fact"],
  ["themealdb", "TheMealDB", "سرگرمی", "دستور غذا", "https://www.themealdb.com/api/json/v1/1"],
  ["cocktaildb", "TheCocktailDB", "سرگرمی", "نوشیدنی‌ها", "https://www.thecocktaildb.com/api/json/v1/1"],
  ["open-brewery", "Open Brewery DB", "سرگرمی", "کارخانه‌های نوشیدنی", "https://api.openbrewerydb.org/v1/breweries"],
  ["bored", "Bored API", "سرگرمی", "پیشنهاد فعالیت", "https://bored-api.appbrewery.com"],
  ["advice-slip", "Advice Slip", "سرگرمی", "توصیه‌های تصادفی", "https://api.adviceslip.com/advice"],
  ["kanye", "Kanye REST", "سرگرمی", "نقل‌قول‌های تصادفی", "https://api.kanye.rest"],
  ["quotable", "Quotable", "سرگرمی", "نقل‌قول‌های معروف", "https://api.quotable.io/quotes/random"],
  ["zenquotes", "ZenQuotes", "سرگرمی", "نقل‌قول‌های الهام‌بخش", "https://zenquotes.io/api/random"],
  ["chuck-norris", "Chuck Norris API", "سرگرمی", "جوک‌های طنز", "https://api.chucknorris.io/jokes/random"],
  ["yesno", "YesNo API", "سرگرمی", "پاسخ بله یا خیر", "https://yesno.wtf/api"],
  ["numbers", "Numbers API", "سرگرمی", "حقایق دربارهٔ اعداد", "http://numbersapi.com"],
  ["coingecko", "CoinGecko", "مالی و رمزارز", "قیمت و دادهٔ رمزارزها", "https://api.coingecko.com/api/v3"],
  ["coincap", "CoinCap", "مالی و رمزارز", "بازار رمزارز", "https://api.coincap.io/v2"],
  ["coinpaprika", "CoinPaprika", "مالی و رمزارز", "دادهٔ رمزارز", "https://api.coinpaprika.com/v1"],
  ["cryptocompare", "CryptoCompare", "مالی و رمزارز", "قیمت و دادهٔ رمزارز", "https://min-api.cryptocompare.com/data/price"],
  ["binance", "Binance API", "مالی و رمزارز", "بازار رمزارز", "https://api.binance.com/api/v3"],
  ["kraken", "Kraken API", "مالی و رمزارز", "بازار رمزارز", "https://api.kraken.com/0/public"],
  ["alpha-vantage", "Alpha Vantage", "مالی و رمزارز", "سهام و فارکس", "https://www.alphavantage.co/query"],
  ["f1", "F1 API", "مالی و رمزارز", "داده‌های مسابقات فرمول یک", "https://api.jolpi.ca/ergast/f1"],
  ["hacker-news", "Hacker News API", "اخبار", "اخبار فناوری", "https://hacker-news.firebaseio.com/v0"],
  ["gdelt", "GDELT", "اخبار", "اخبار و رویدادهای جهانی", "https://api.gdeltproject.org/api/v2"],
  ["reddit", "Reddit API", "اخبار", "داده‌های عمومی Reddit", "https://www.reddit.com/r/all.json"],
  ["github", "GitHub REST API", "کدنویسی", "مخازن و کد", "https://api.github.com"],
  ["gitlab", "GitLab API", "کدنویسی", "پروژه‌های GitLab", "https://gitlab.com/api/v4"],
  ["bitbucket", "Bitbucket API", "کدنویسی", "مخازن Bitbucket", "https://api.bitbucket.org/2.0"],
  ["libraries-io", "Libraries.io API", "کدنویسی", "اطلاعات کتابخانه‌ها", "https://libraries.io/api"],
];

export const freeConnectors: FreeConnector[] = rows.map(([id, name, category, detail, endpoint]) => ({ id, name, category, detail, endpoint, keyRequired: false }));
export const freeConnectorCategories = Array.from(new Set(freeConnectors.map((item) => item.category)));
