import { useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, Check, Clipboard, Crown, History, KeyRound, LockKeyhole, Settings2, Sparkles, Trash2 } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { agentProfiles } from "../../../shared/agentProfiles";
import { getPlan } from "../../../shared/plans";

const statusLabels: Record<string, string> = {
  pending: "در انتظار بررسی",
  verified: "تأیید شده",
  rejected: "رد شده",
};

const statusClasses: Record<string, string> = {
  pending: "bg-[#fff6dd] text-[#866300]",
  verified: "bg-[#e8f6e9] text-[#256b2c]",
  rejected: "bg-[#fff0f0] text-[#9b3838]",
};

function formatDate(value: Date | string | null | undefined, empty = "—") {
  if (!value) return empty;
  return new Date(value).toLocaleString("fa-IR", { dateStyle: "medium", timeStyle: "short" });
}

function AccountContent() {
  const access = trpc.subscription.me.useQuery(undefined, { retry: false });
  const payments = trpc.payment.history.useQuery(undefined, { retry: false, enabled: Boolean(access.data) });
  const plan = access.data?.plan;
  const subscription = access.data?.subscription;
  const isAdmin = access.data?.isAdmin;
  const videoCredentials = trpc.subscription.videoCredentials.useQuery(undefined, { retry: false });
  const saveVideoCredential = trpc.subscription.saveVideoCredential.useMutation({ onSuccess: () => { void videoCredentials.refetch(); setVideoKey(""); } });
  const deleteVideoCredential = trpc.subscription.deleteVideoCredential.useMutation({ onSuccess: () => { void videoCredentials.refetch(); } });
  const [videoProvider, setVideoProvider] = useState<"Runway" | "Seedance">("Runway");
  const [videoKey, setVideoKey] = useState("");
  const expiryText = isAdmin ? "دسترسی داخلی بدون انقضا" : subscription?.isLifetime === 1 ? "مادام‌العمر" : formatDate(subscription?.expiresAt, "هنوز اشتراک فعالی ثبت نشده است");
  const accountStatus = isAdmin ? "Admin · فعال برای تست" : access.data?.source === "subscription" ? (subscription?.status === "active" ? "فعال" : statusLabels[subscription?.status ?? ""] ?? subscription?.status) : "بدون اشتراک فعال";

  return <main dir="rtl" className="min-h-screen bg-[#f6f6f4] px-4 py-7 text-[#111] md:px-8">
    <div className="mx-auto max-w-6xl">
      <header className="flex flex-wrap items-start justify-between gap-4 border-b border-[#dededb] pb-6">
        <div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#888]">Persian Dark Horse · FEZI AI</p><h1 className="mt-2 text-3xl font-semibold">پنل کاربری</h1><p className="mt-2 text-sm text-[#666]">وضعیت حساب، اشتراک، پرداخت‌ها و تیم Agentها در یک نگاه.</p></div>
        <Link href="/" className="inline-flex items-center gap-2 rounded-xl border border-[#ddd] bg-white px-4 py-2 text-xs hover:bg-black hover:text-white">شروع گفتگو <ArrowLeft size={14} /></Link>
      </header>

      {access.isError && <div className="mt-6 rounded-2xl border border-[#e9caca] bg-[#fff5f5] p-4 text-sm text-[#8c3131]">برای مشاهدهٔ پنل کاربری باید با حساب FEZI AI وارد شوید.</div>}
      {plan && <>
        <section className="mt-7 grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
          <div className="rounded-3xl bg-black p-6 text-white shadow-xl md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-white/45">پلن فعلی</p><h2 className="mt-3 text-3xl font-bold">{plan.nameFa}</h2><p className="mt-1 text-sm text-white/55">{plan.nameEn}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10">{isAdmin ? <Crown size={22} /> : <Sparkles size={22} />}</div></div><p className="mt-7 text-sm leading-7 text-white/65">{isAdmin ? "دسترسی مدیر برای تست ساخت FEZI AI فعال است." : access.data?.source === "free" ? "تا زمان launch عمومی، استفاده از قابلیت‌ها برای کاربران بیرونی نیازمند خرید اشتراک است." : plan.summary}</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/subscription" className="rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black hover:bg-white/85">مدیریت و ارتقای پلن</Link><Link href="/welcome?tab=skills" className="rounded-xl border border-white/20 px-4 py-2.5 text-xs text-white hover:bg-white/10">تنظیمات Agentها</Link></div></div>
          <div className="rounded-3xl border border-[#dededb] bg-white p-6 md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#888]">وضعیت حساب</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div><p className="text-xs text-[#888]">وضعیت پلن</p><p className="mt-1 text-lg font-semibold">{accountStatus}</p></div><div><p className="text-xs text-[#888]">زمان انقضا</p><p className="mt-1 text-lg font-semibold">{expiryText}</p></div><div><p className="text-xs text-[#888]">آخرین به‌روزرسانی</p><p className="mt-1 text-sm font-medium">{formatDate(subscription?.updatedAt)}</p></div></div></div>
        </section>

        <section className="mt-7 rounded-3xl border border-[#dededb] bg-white p-6 md:p-8" aria-labelledby="payment-history-title"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black text-white"><History size={18} /></div><div><h2 id="payment-history-title" className="text-xl font-bold">تاریخچه پرداخت‌ها</h2><p className="mt-1 text-xs text-[#777]">تمام درخواست‌های ثبت‌شده با این حساب و وضعیت بررسی آن‌ها.</p></div></div><span className="rounded-full bg-[#f0f0ee] px-3 py-1 text-xs">{payments.data?.length ?? 0} درخواست</span></div>{payments.isLoading && <div className="mt-6 rounded-2xl bg-[#f8f8f6] p-5 text-center text-xs text-[#777]">در حال دریافت تاریخچه پرداخت...</div>}{payments.isError && <div className="mt-6 rounded-2xl border border-[#eadada] bg-[#fff8f8] p-4 text-xs text-[#8c3131]">تاریخچهٔ پرداخت در حال حاضر قابل دریافت نیست.</div>}{!payments.isLoading && !payments.isError && (payments.data?.length ?? 0) === 0 && <div className="mt-6 rounded-2xl border border-dashed border-[#d8d8d5] p-7 text-center"><Clipboard className="mx-auto text-[#999]" size={24} /><p className="mt-3 text-sm font-medium">هنوز پرداختی ثبت نشده است</p><p className="mt-1 text-xs text-[#888]">برای انتخاب پلن و ثبت TXID به صفحهٔ خرید اشتراک بروید.</p><Link href="/subscription" className="mt-4 inline-flex rounded-xl bg-black px-4 py-2 text-xs text-white">مشاهده پلن‌ها</Link></div>}{(payments.data?.length ?? 0) > 0 && <div className="mt-5 space-y-3">{payments.data?.map((payment) => <article key={payment.id} className="rounded-2xl border border-[#e5e5e2] bg-[#fbfbfa] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">{getPlan(payment.planId).nameFa} <span className="font-normal text-[#777]"> · {payment.amount} {payment.currency}</span></p><p className="mt-1 text-[11px] text-[#888]">ثبت شده در {formatDate(payment.createdAt)}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] ${statusClasses[payment.status] ?? "bg-[#eee] text-[#555]"}`}>{statusLabels[payment.status] ?? payment.status}</span></div><div className="mt-3 grid gap-2 text-[11px] sm:grid-cols-[1fr_auto]"><div className="rounded-xl bg-white p-3"><span className="text-[#888]">TXID</span><p dir="ltr" className="mt-1 break-all font-mono text-[#333]">{payment.txid}</p></div>{payment.memo && <div className="rounded-xl bg-white p-3"><span className="text-[#888]">Memo / Tag</span><p dir="ltr" className="mt-1 break-all font-mono text-[#333]">{payment.memo}</p></div>}</div></article>)}</div>}</section>

        <section className="mt-7 rounded-3xl border border-[#dededb] bg-white p-6 md:p-8" aria-labelledby="video-keys-title"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black text-white"><KeyRound size={18} /></div><div><h2 id="video-keys-title" className="text-xl font-bold">کلیدهای تولید ویدیو</h2><p className="mt-1 text-xs leading-5 text-[#777]">کلید Runway یا Seedance شما به‌صورت رمزگذاری‌شده ذخیره می‌شود و مقدار کامل آن هرگز نمایش داده نمی‌شود.</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{(["Runway", "Seedance"] as const).map((provider) => { const credential = videoCredentials.data?.find((item) => item.provider === provider); return <div key={provider} className="rounded-2xl border border-[#e5e5e2] bg-[#fbfbfa] p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold">{provider}</p>{credential ? <span className="rounded-full bg-[#e8f6e9] px-2 py-1 text-[10px] text-[#256b2c]">متصل · ••••{credential.lastFour}</span> : <span className="rounded-full bg-[#f0f0ee] px-2 py-1 text-[10px] text-[#777]">نیازمند کلید</span>}</div><p className="mt-2 text-[10px] leading-5 text-[#888]">{provider === "Runway" ? "برای تولید ویدیوی MP4 از مدل‌های Runway." : "برای فعال‌کردن مسیر تولید ویدیوی Seedance."}</p>{credential && <button onClick={() => deleteVideoCredential.mutate({ id: credential.id })} disabled={deleteVideoCredential.isPending} className="mt-3 inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-[10px] text-[#a33] hover:bg-[#fff0f0] disabled:opacity-50"><Trash2 size={13} /> حذف کلید</button>}</div>; })}</div><div className="mt-5 grid gap-3 md:grid-cols-[160px_1fr_auto]"><select value={videoProvider} onChange={(event) => setVideoProvider(event.target.value as "Runway" | "Seedance")} className="h-10 rounded-xl border border-[#ddd] bg-white px-3 text-xs"><option>Runway</option><option>Seedance</option></select><input type="password" value={videoKey} onChange={(event) => setVideoKey(event.target.value)} placeholder={`API Key ${videoProvider} را وارد کنید`} autoComplete="off" className="h-10 rounded-xl border border-[#ddd] bg-white px-3 text-xs" /><button onClick={() => saveVideoCredential.mutate({ provider: videoProvider, secret: videoKey })} disabled={videoKey.trim().length < 8 || saveVideoCredential.isPending} className="rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">{saveVideoCredential.isPending ? "در حال ذخیره..." : "ذخیره امن"}</button></div>{saveVideoCredential.isError && <p className="mt-3 text-xs text-[#a33]">ذخیره کلید انجام نشد؛ تنظیمات رمزگذاری سرور یا مقدار کلید را بررسی کنید.</p>}<p className="mt-3 text-[10px] text-[#999]">کلیدها به حساب کاربری شما وابسته‌اند و در پاسخ‌های API یا کد frontend ارسال نمی‌شوند.</p></section>

        <section className="mt-7 rounded-3xl border border-[#dededb] bg-white p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#888]">AI TEAM</p><h2 className="mt-2 text-2xl font-bold">تیم Agentها</h2></div><span className="rounded-full bg-[#f0f0ee] px-3 py-1 text-xs">{isAdmin ? agentProfiles.length : access.data?.source === "subscription" ? plan.agents.length : 0} فعال از {agentProfiles.length}</span></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{agentProfiles.map((agent) => { const allowed = Boolean(isAdmin || (access.data?.source === "subscription" && plan.agents.includes(agent.id))); return <div key={agent.id} className={`rounded-2xl border p-4 ${allowed ? "border-[#dcdcd8] bg-[#fbfbfa]" : "border-[#eadada] bg-[#fff8f8]"}`}><div className="flex items-start justify-between gap-2"><div className="h-12 w-12 overflow-hidden rounded-xl bg-black">{agent.image && <img src={agent.image} alt={`تصویر ${agent.name}`} className="h-full w-full object-cover" />}</div>{allowed ? <Check size={16} /> : <LockKeyhole size={16} className="text-[#a56c6c]" />}</div><p className="mt-4 text-sm font-semibold">{agent.name}</p><p className="mt-1 text-[10px] text-[#777]">{allowed ? "Available" : "Premium · قفل"}</p>{allowed ? <Link href="/" className="mt-4 block text-[10px] underline">شروع گفتگو</Link> : <Link href="/subscription" className="mt-4 block text-[10px] text-[#9a4545] underline">ارتقای پلن</Link>}</div>; })}</div></section>
        <section className="mt-7 grid gap-3 md:grid-cols-3"><Link href="/subscription" className="rounded-2xl border border-[#dededb] bg-white p-5 hover:border-black"><Crown size={18} /><p className="mt-4 text-sm font-semibold">خرید اشتراک ماهانه</p><p className="mt-1 text-xs text-[#777]">انتخاب پلن و ثبت TXID</p></Link><Link href="/welcome?tab=connectors" className="rounded-2xl border border-[#dededb] bg-white p-5 hover:border-black"><Settings2 size={18} /><p className="mt-4 text-sm font-semibold">Connectors و مهارت‌ها</p><p className="mt-1 text-xs text-[#777]">شخصی‌سازی Agent فعال</p></Link><Link href="/legal" className="rounded-2xl border border-[#dededb] bg-white p-5 hover:border-black"><Sparkles size={18} /><p className="mt-4 text-sm font-semibold">قوانین و معرفی</p><p className="mt-1 text-xs text-[#777]">دربارهٔ Persian Dark Horse</p></Link></section>
      </>}
    </div>
  </main>;
}

export default function Account() { return <DashboardLayout><AccountContent /></DashboardLayout>; }
