import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, Check, Code2, ExternalLink, X } from "lucide-react";

type FreeApi = { name: string; description: string; site: string; endpoint: string; auth: string; category: string; sample: string };
const api = (name: string, description: string, site: string, endpoint: string, category: string, auth = "بدون کلید") => ({ name, description, site, endpoint, auth, category, sample: `fetch("${endpoint}").then(r => r.json()).then(console.log)` });
const freeApis: FreeApi[] = [
  api("Open-Meteo", "آب‌وهوا و پیش‌بینی جوی", "https://open-meteo.com", "https://api.open-meteo.com/v1/forecast?latitude=35.7&longitude=51.4&current=temperature_2m", "آب‌وهوا"),
  api("REST Countries", "اطلاعات کشورها و پرچم‌ها", "https://restcountries.com", "https://restcountries.com/v3.1/all", "داده عمومی"),
  api("Open Food Facts", "اطلاعات محصولات غذایی و بارکد", "https://world.openfoodfacts.org", "https://world.openfoodfacts.org/api/v2/product/737628064502.json", "غذا"),
  api("CoinGecko", "قیمت و بازار رمزارزها", "https://www.coingecko.com/en/api", "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd", "مالی"),
  api("Frankfurter", "نرخ ارز از داده‌های بانک مرکزی اروپا", "https://www.frankfurter.app", "https://api.frankfurter.app/latest?from=USD&to=EUR", "مالی"),
  api("Nager.Date", "تعطیلات رسمی کشورها", "https://date.nager.at", "https://date.nager.at/api/v3/NextPublicHolidays/US", "تقویم"),
  api("Open Library", "اطلاعات کتاب‌ها و نویسندگان", "https://openlibrary.org/developers/api", "https://openlibrary.org/search.json?q=the+little+prince", "کتاب"),
  api("JSONPlaceholder", "داده آزمایشی REST", "https://jsonplaceholder.typicode.com", "https://jsonplaceholder.typicode.com/posts/1", "توسعه"),
  api("httpbin", "آزمایش درخواست‌های HTTP", "https://httpbin.org", "https://httpbin.org/get", "توسعه"),
  api("Jikan", "API غیررسمی MyAnimeList", "https://jikan.moe", "https://api.jikan.moe/v4/anime?q=naruto", "سرگرمی"),
  api("Quran Cloud", "قرآن و ترجمه‌ها", "https://alquran.cloud/api", "https://api.alquran.cloud/v1/surah/1", "فرهنگ"),
  api("Gutendex", "کتاب‌های Project Gutenberg", "https://gutendex.com", "https://gutendex.com/books?search=shakespeare", "کتاب"),
  api("Kroki", "تولید نمودار و دیاگرام", "https://kroki.io", "https://kroki.io/mermaid/svg/eNqLU0jOzy0oSi0uzs9TKEktLgYAQh4G7Q", "نمودار"),
  api("Iconify", "آیکون‌های SVG", "https://iconify.design", "https://api.iconify.design/collection?prefix=mdi", "طراحی"),
  api("IPify", "شناسایی IP عمومی", "https://www.ipify.org", "https://api.ipify.org?format=json", "شبکه"),
  api("Agify", "تخمین سن از روی نام", "https://agify.io", "https://api.agify.io?name=fezi", "داده تفریحی"),
  api("Genderize", "تخمین جنسیت از روی نام", "https://genderize.io", "https://api.genderize.io?name=alex", "داده تفریحی"),
  api("Nationalize", "تخمین ملیت از روی نام", "https://nationalize.io", "https://api.nationalize.io?name=alex", "داده تفریحی"),
  api("Dog CEO", "تصاویر سگ", "https://dog.ceo/dog-api", "https://dog.ceo/api/breeds/image/random", "تصویر"),
  api("The Cat API", "تصاویر گربه", "https://thecatapi.com", "https://api.thecatapi.com/v1/images/search", "تصویر", "کلید اختیاری"),
  api("Cat Facts", "حقایق تصادفی درباره گربه‌ها", "https://catfact.ninja", "https://catfact.ninja/fact", "سرگرمی"),
  api("PokeAPI", "اطلاعات Pokémon", "https://pokeapi.co", "https://pokeapi.co/api/v2/pokemon/pikachu", "سرگرمی"),
  api("PokéAPI GraphQL", "نسخه GraphQL اطلاعات Pokémon", "https://pokeapi.co", "https://beta.pokeapi.co/graphql/legacy", "GraphQL"),
  api("Rick and Morty API", "شخصیت‌ها و قسمت‌ها", "https://rickandmortyapi.com", "https://rickandmortyapi.com/api/character/1", "سرگرمی"),
  api("SWAPI", "اطلاعات Star Wars", "https://swapi.dev", "https://swapi.dev/api/people/1/", "سرگرمی"),
  api("Studio Ghibli API", "فیلم‌های استودیو جیبلی", "https://ghibliapi.vercel.app", "https://ghibliapi.vercel.app/films", "فیلم"),
  api("TheMealDB", "دستورهای آشپزی", "https://www.themealdb.com/api.php", "https://www.themealdb.com/api/json/v1/1/search.php?s=pasta", "غذا"),
  api("TheCocktailDB", "اطلاعات نوشیدنی‌ها", "https://www.thecocktaildb.com/api.php", "https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita", "غذا"),
  api("Open Brewery DB", "اطلاعات کارخانه‌های نوشیدنی", "https://www.openbrewerydb.org", "https://api.openbrewerydb.org/v1/breweries?by_city=seattle", "داده عمومی"),
  api("Bored API", "پیشنهاد فعالیت", "https://bored-api.appbrewery.com", "https://bored-api.appbrewery.com/random", "سرگرمی"),
  api("Advice Slip", "توصیه‌های تصادفی", "https://api.adviceslip.com", "https://api.adviceslip.com/advice", "سرگرمی"),
  api("Kanye REST", "نقل‌قول‌های تصادفی", "https://kanye.rest", "https://api.kanye.rest", "سرگرمی"),
  api("Quotable", "نقل‌قول‌های معروف", "https://quotable.io", "https://api.quotable.io/random", "متن"),
  api("ZenQuotes", "نقل‌قول‌ها", "https://zenquotes.io", "https://zenquotes.io/api/random", "متن", "رایگان با محدودیت"),
  api("Chuck Norris API", "جوک‌های Chuck Norris", "https://api.chucknorris.io", "https://api.chucknorris.io/jokes/random", "سرگرمی"),
  api("Evil Insult Generator", "تولید عبارت‌های طنز", "https://evilinsult.com", "https://evilinsult.com/generate_insult.php?lang=en&type=json", "سرگرمی"),
  api("YesNo API", "پاسخ بله/خیر و تصویر", "https://yesno.wtf", "https://yesno.wtf/api", "سرگرمی"),
  api("Numbers API", "حقایق مربوط به اعداد", "http://numbersapi.com", "http://numbersapi.com/42/trivia?json", "متن"),
  api("Universities List", "فهرست دانشگاه‌ها", "https://universities.hipolabs.com", "http://universities.hipolabs.com/search?country=Iran", "آموزش"),
  api("World Time API", "زمان مناطق مختلف", "https://worldtimeapi.org", "https://worldtimeapi.org/api/timezone/Asia/Tehran", "زمان"),
  api("IPinfo", "اطلاعات IP", "https://ipinfo.io", "https://ipinfo.io/json", "شبکه", "توکن اختیاری"),
  api("ip-api", "موقعیت تقریبی IP", "https://ip-api.com", "http://ip-api.com/json", "مکان"),
  api("OpenCage", "تبدیل آدرس و مختصات", "https://opencagedata.com", "https://api.opencagedata.com/geocode/v1/json?q=Tehran&key=YOUR_KEY", "مکان", "نیازمند کلید رایگان"),
  api("Nominatim", "جست‌وجوی OpenStreetMap", "https://nominatim.org", "https://nominatim.openstreetmap.org/search?q=Tehran&format=jsonv2", "نقشه"),
  api("Overpass API", "جست‌وجو در داده‌های OpenStreetMap", "https://overpass-api.de", "https://overpass-api.de/api/interpreter?data=[out:json];node(35.6,51.3,35.8,51.5);out%201;", "نقشه"),
  api("OpenAQ", "کیفیت هوا", "https://openaq.org", "https://api.openaq.org/v3/locations?limit=1", "محیط زیست", "کلید ممکن است برای نسخه‌های جدید لازم باشد"),
  api("NASA APIs", "داده‌های فضایی", "https://api.nasa.gov", "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY", "فضا", "DEMO_KEY / کلید رایگان"),
  api("USGS Earthquake", "زلزله‌ها", "https://earthquake.usgs.gov", "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson", "محیط زیست"),
  api("NOAA Weather", "هوا و اقلیم", "https://www.weather.gov/documentation/services-web-api", "https://api.weather.gov/points/39.7456,-97.0892", "آب‌وهوا"),
  api("Sunrise-Sunset", "طلوع و غروب", "https://sunrise-sunset.org/api", "https://api.sunrise-sunset.org/json?lat=35.7&lng=51.4&formatted=0", "زمان"),
];

export default function FreeAPIs() { const [selected, setSelected] = useState<FreeApi | null>(null); const categories = useMemo(() => ["همه", ...Array.from(new Set(freeApis.map((item) => item.category)))], []); const [category, setCategory] = useState("همه"); const filtered = category === "همه" ? freeApis : freeApis.filter((item) => item.category === category); return <main className="min-h-screen bg-[#f7f7f5] px-5 py-10 text-[#111] md:px-12"><div className="mx-auto max-w-6xl"><Link href="/api" className="inline-flex items-center gap-2 text-sm text-[#666] hover:text-black"><ArrowRight size={16} /> بازگشت به APIهای FEZI</Link><header className="mt-12 max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-[#888]">فهرست APIهای FEZI</p><h1 className="mt-4 font-serif text-4xl font-semibold md:text-6xl">APIهای رایگان</h1><p className="mt-5 text-base leading-8 text-[#666]">فهرست APIهای عمومی و رایگان برای نمونه‌سازی، ابزارهای Agent، دادهٔ زنده و تجربه‌های خلاق. رایگان‌بودن به‌معنی نبودن محدودیت نرخ یا مجوز استفاده نیست.</p></header><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs ${category === item ? "bg-black text-white" : "bg-white text-[#666]"}`}>{item}</button>)}</div><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <button type="button" key={item.name} onClick={() => setSelected(item)} className="rounded-2xl border border-[#e2e2df] bg-white p-4 text-right transition hover:-translate-y-0.5 hover:border-black hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{item.name}</h2><p className="mt-1 text-[11px] text-[#888]">{item.category}</p></div><span className="rounded-full bg-[#eef5ed] px-2 py-1 text-[10px] text-[#376338]">{item.auth === "بدون کلید" ? "بدون کلید" : "کلید/شرط"}</span></div><p className="mt-3 text-xs leading-5 text-[#666]">{item.description}</p><p className="mt-3 truncate font-mono text-[10px] text-[#999]">{item.endpoint}</p></button>)}</section><p className="mt-8 text-xs leading-6 text-[#888]">تعداد سرویس‌های فهرست‌شده: {freeApis.length}. پیش از استفادهٔ تجاری، مستندات رسمی، شرایط مجوز، ذکر منبع و محدودیت نرخ هر سرویس را بررسی کنید.</p></div>{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><section role="dialog" aria-modal="true" aria-labelledby="free-api-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl md:p-8" dir="rtl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#999]">پروفایل API رایگان</p><h2 id="free-api-title" className="mt-2 text-2xl font-semibold">{selected.name}</h2></div><button type="button" onClick={() => setSelected(null)} aria-label="بستن" className="rounded-xl p-2 text-[#666] hover:bg-[#f1f1ef]"><X size={19} /></button></div><p className="mt-5 text-sm leading-7 text-[#555]">{selected.description}</p><dl className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[#f6f6f4] p-4"><dt className="text-[10px] text-[#888]">وب‌سایت</dt><dd className="mt-1 text-sm"><a href={selected.site} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 underline">منبع رسمی <ExternalLink size={13} /></a></dd></div><div className="rounded-2xl bg-[#f6f6f4] p-4"><dt className="text-[10px] text-[#888]">احراز هویت</dt><dd className="mt-1 text-sm">{selected.auth}</dd></div></dl><div className="mt-5"><p className="text-xs font-semibold">نشانی درخواست نمونه</p><code className="mt-2 block overflow-x-auto rounded-2xl bg-[#111] p-4 text-left text-[11px] leading-6 text-[#eee]" dir="ltr">{selected.endpoint}</code></div><div className="mt-5"><p className="flex items-center gap-2 text-xs font-semibold"><Code2 size={15} /> کد جاوااسکریپت</p><pre className="mt-2 overflow-x-auto rounded-2xl bg-[#111] p-4 text-left text-[11px] leading-6 text-[#eee]" dir="ltr"><code>{selected.sample}</code></pre></div><div className="mt-6 flex items-center gap-2 text-xs text-[#4b6b4b]"><Check size={15} /> نمونه برای شروع آماده است؛ محدودیت‌ها را از منبع رسمی بررسی کنید.</div></section></div>}</main>; }
