import { useMemo, useState } from "react";
import { ArrowRight, Check, ExternalLink, Image, MessageCircle, Play, Search, Sparkles, BrainCircuit, Cloud, Boxes } from "lucide-react";
import { Link, useLocation } from "wouter";
import { AGENT_MODEL_DEFAULTS, MODEL_CATEGORIES, MODEL_CATALOG, modelAccessLabel, type ModelCategory } from "../../../shared/modelCatalog";
import { agentProfiles } from "../../../shared/agentProfiles";

const icons: Record<ModelCategory, typeof MessageCircle> = { chat: MessageCircle, reasoning: BrainCircuit, image: Image, video: Play, openai: Sparkles, cloud: Cloud, wan: Boxes };

export default function Models() {
  const [, navigate] = useLocation();
  const [agentId, setAgentId] = useState("manika");
  const [category, setCategory] = useState<ModelCategory | "all">("all");
  const [query, setQuery] = useState("");
  const defaults = AGENT_MODEL_DEFAULTS[agentId] ?? AGENT_MODEL_DEFAULTS.manika;
  const filtered = useMemo(() => MODEL_CATALOG.filter((model) => (category === "all" || model.category === category) && `${model.name} ${model.provider} ${model.description}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  function selectModel(id: string, supportsChat: boolean) {
    localStorage.setItem("fezi-selected-model", id);
    const model = MODEL_CATALOG.find((item) => item.id === id);
    if (supportsChat && model?.modelId?.includes(":free")) localStorage.setItem("fezi-routeway-model", model.modelId);
    if (supportsChat) navigate("/");
    else if (model?.category === "image") navigate(`/studio/image?provider=${encodeURIComponent(model.name)}`);
    else if (model?.category === "video" || model?.category === "wan") navigate(`/studio/video?provider=${encodeURIComponent(model.name)}`);
  }
  return <main dir="rtl" className="min-h-screen bg-[#f7f4f0] px-4 py-6 text-[#222] sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#ddd8d2] pb-5"><div className="flex items-center gap-3"><Link href="/" className="rounded-xl p-2 hover:bg-white" aria-label="بازگشت"><ArrowRight size={18} /></Link><div><p className="font-serif text-2xl font-semibold">مرکز مدل‌ها</p><p className="mt-1 text-xs text-[#888]">FEZI AI · انتخاب موتور برای هر Agent</p></div></div><Link href="/" className="rounded-xl bg-black px-4 py-2.5 text-xs font-semibold text-white">بازگشت به چت</Link></header>
    <section className="mt-8 rounded-[28px] bg-black p-6 text-white sm:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[0.2em] text-white/45">MODEL ROUTER</p><h1 className="mt-3 text-3xl font-semibold sm:text-5xl">مدل مناسب را انتخاب کنید</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/65">برای هر Agent پنج مدل پیشنهادی آماده شده است. فضی می‌تواند با تمام مدل‌های کاتالوگ کار کند؛ استفادهٔ واقعی هر مدل به اتصال، کلید و سهمیهٔ همان Provider وابسته است.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs">{MODEL_CATALOG.length} مدل کاتالوگ‌شده</div></div><div className="mt-7 flex flex-wrap gap-2">{agentProfiles.map((agent) => <button key={agent.id} onClick={() => setAgentId(agent.id)} className={`flex items-center gap-2 rounded-2xl px-3 py-2 text-xs transition ${agentId === agent.id ? "bg-white text-black" : "bg-white/10 text-white/75 hover:bg-white/15"}`}><img src={agent.image} alt="" className="h-7 w-7 rounded-lg object-cover" />{agent.name}</button>)}</div></section>
    <section className="mt-7 rounded-3xl border border-[#dedad5] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">پیشنهادهای {agentProfiles.find((agent) => agent.id === agentId)?.name}</h2><p className="mt-1 text-xs text-[#888]">پنج مدل پیش‌فرض اختصاصی این Agent</p></div><span className="rounded-full bg-[#f1f1ef] px-3 py-2 text-[10px] text-[#666]">قابل تغییر در هر زمان</span></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{defaults.map((id) => { const model = MODEL_CATALOG.find((item) => item.id === id); return model ? <ModelCard key={id} model={model} featured onSelect={selectModel} /> : null; })}</div></section>
    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#888]">FULL CATALOG</p><h2 className="mt-2 text-2xl font-semibold">تمامی مدل‌ها</h2><p className="mt-2 text-sm text-[#777]">مدل‌های چت، استدلالی، OpenAI، Cloud، تصویر، ویدیو و Wan.</p></div><label className="relative block w-full sm:w-72"><Search size={15} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#999]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جست‌وجوی مدل یا Provider" className="h-11 w-full rounded-xl border border-[#d9d5d0] bg-white pr-9 pl-3 text-xs outline-none focus:border-black" /></label></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{[{ id: "all", label: "همه" }, ...MODEL_CATEGORIES].map((item) => <button key={item.id} onClick={() => setCategory(item.id as ModelCategory | "all")} className={`shrink-0 rounded-xl px-3 py-2 text-xs ${category === item.id ? "bg-black text-white" : "bg-white text-[#666] ring-1 ring-[#dedad5] hover:ring-black"}`}>{item.label}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((model) => <ModelCard key={model.id} model={model} onSelect={selectModel} />)}</div>{filtered.length === 0 && <div className="mt-5 rounded-2xl border border-dashed border-[#ccc] bg-white p-8 text-center text-sm text-[#777]">مدلی با این مشخصات پیدا نشد.</div>}</section>
    <p className="mt-8 text-[11px] leading-6 text-[#999]">برچسب «رایگان» به معنی رایگان نامحدود نیست. free-tier، کلید، quota، منطقه و billing Provider ممکن است تغییر کند؛ وضعیت هر مدل در این صفحه برای تصمیم‌گیری شفاف نمایش داده می‌شود.</p></div></main>;
}

function ModelCard({ model, featured = false, onSelect }: { model: (typeof MODEL_CATALOG)[number]; featured?: boolean; onSelect: (id: string, supportsChat: boolean) => void }) {
  const Icon = icons[model.category];
  return <article className={`rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-md ${featured ? "border-black bg-[#fbfbfa]" : "border-[#e2dfda] bg-white"}`}><div className="flex items-start justify-between gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-black text-white"><Icon size={16} /></span><span className={`rounded-full px-2 py-1 text-[9px] ${model.access === "free" || model.access === "connected" ? "bg-[#e7f5e8] text-[#256b2c]" : model.access === "free-tier" ? "bg-[#fff4d8] text-[#80621e]" : "bg-[#f0eeee] text-[#777]"}`}>{modelAccessLabel[model.access]}</span></div><h3 className="mt-4 text-sm font-semibold">{model.name}</h3><p className="mt-1 text-[10px] text-[#888]">{model.provider}</p><p className="mt-3 min-h-10 text-[10px] leading-5 text-[#666]">{model.description}</p><div className="mt-3 flex flex-wrap gap-1">{model.agents.map((agentId) => <span key={agentId} className={`rounded-md px-1.5 py-1 text-[9px] ${agentId === "fezi" ? "bg-black text-white" : "bg-[#f1f1ef] text-[#777]"}`}>{agentId === "fezi" ? "فضی" : agentId}</span>)}</div><div className="mt-4 flex items-center gap-2"><button onClick={() => onSelect(model.id, model.supportsChat)} className="flex-1 rounded-xl bg-black px-2 py-2.5 text-[10px] font-semibold text-white hover:bg-[#222]">{model.supportsChat ? "انتخاب برای چت" : "ورود به استودیو"}</button><a href={model.sourceUrl} target="_blank" rel="noreferrer" className="rounded-xl border border-[#ddd] p-2.5 text-[#777] hover:border-black hover:text-black" aria-label={`منبع رسمی ${model.name}`}><ExternalLink size={14} /></a></div></article>;
}
